// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "100001",
    name: "Somchai Prasert",
    email: "somchai.prasert@example.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0812345678",
    subjects: ["Math", "Geometry"],
    classes: ["M1/1", "M2/2", "M3/3"],
    address: "123 Sukhumvit Rd, Bangkok, Thailand",
  },
  {
    id: 2,
    teacherId: "100002",
    name: "Sureeporn Chaiyawan",
    email: "sureeporn.chaiyawan@example.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0912345678",
    subjects: ["Physics", "Chemistry"],
    classes: ["M5/1", "M4/2", "M3/3"],
    address: "456 Silom Rd, Bangkok, Thailand",
  },
  {
    id: 3,
    teacherId: "100003",
    name: "Anucha Srisuk",
    email: "anucha.srisuk@example.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0612345678",
    subjects: ["Biology"],
    classes: ["M5/1", "M4/2", "M3/3"],
    address: "789 Ratchada Rd, Bangkok, Thailand",
  },
  {
    id: 4,
    teacherId: "100004",
    name: "Kanchana Phongphrai",
    email: "kanchana.phongphrai@example.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0812345678",
    subjects: ["History"],
    classes: ["M5/1", "M4/2", "M3/3"],
    address: "321 Ladprao Rd, Bangkok, Thailand",
  },
  {
    id: 5,
    teacherId: "100005",
    name: "Somsak Yodchai",
    email: "somsak.yodchai@example.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0912345678",
    subjects: ["Music", "Art"],
    classes: ["M5/1", "M4/2", "M3/3"],
    address: "234 Phahonyothin Rd, Bangkok, Thailand",
  },
  {
    id: 6,
    teacherId: "100006",
    name: "Nongnuch Saowaluk",
    email: "nongnuch.saowaluk@example.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0612345678",
    subjects: ["Physics"],
    classes: ["M5/1", "M4/2", "M3/3"],
    address: "567 Sathorn Rd, Bangkok, Thailand",
  },
  {
    id: 7,
    teacherId: "100007",
    name: "Kritsada Wongchai",
    email: "kritsada.wongchai@example.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0812345678",
    subjects: ["English", "Thai Language"],
    classes: ["M5/1", "M4/2", "M3/3"],
    address: "987 Ramkhamhaeng Rd, Bangkok, Thailand",
  },
  {
    id: 8,
    teacherId: "100008",
    name: "Supaporn Meesuk",
    email: "supaporn.meesuk@example.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0912345678",
    subjects: ["Math", "Geometry"],
    classes: ["M5/1", "M4/2", "M3/3"],
    address: "654 Charoenkrung Rd, Bangkok, Thailand",
  },
  {
    id: 9,
    teacherId: "100009",
    name: "Wiroj Phanit",
    email: "wiroj.phanit@example.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0812345678",
    subjects: ["Literature", "English"],
    classes: ["M5/1", "M4/2", "M3/3"],
    address: "789 Rama 4 Rd, Bangkok, Thailand",
  },
  {
    id: 10,
    teacherId: "100010",
    name: "Pichai Samut",
    email: "pichai.samut@example.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0912345678",
    subjects: ["Biology"],
    classes: ["M5/1", "M4/2", "M3/3"],
    address: "321 Sukhumvit 71, Bangkok, Thailand",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "6101010001",
    name: "Arthit Boonchai",
    email: "arthit.boonchai@gmail.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0812345678",
    grade: 5,
    class: "5/1",
    address: "45 Soi Sukhumvit 22, Klongtoey, Bangkok",
  },
  {
    id: 2,
    studentId: "6101010002",
    name: "Nicha Suphan",
    email: "nicha.suphan@gmail.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0812345679",
    grade: 5,
    class: "5/1",
    address: "32 Ladprao Road, Chatuchak, Bangkok",
  },
  {
    id: 3,
    studentId: "6101010003",
    name: "Somchai Yimprasert",
    email: "somchai.yimprasert@gmail.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0812345680",
    grade: 5,
    class: "5/1",
    address: "78 Charoenkrung Road, Bangrak, Bangkok",
  },
  {
    id: 4,
    studentId: "6101010004",
    name: "Anong Thongchai",
    email: "anong.thongchai@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0812345681",
    grade: 5,
    class: "5/2",
    address: "15 Silom Road, Bangrak, Bangkok",
  },
  {
    id: 5,
    studentId: "6101010005",
    name: "Sarinya Kaewmanee",
    email: "sarinya.kaewmanee@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0812345682",
    grade: 5,
    class: "5/2",
    address: "29 Phaholyothin Road, Chatuchak, Bangkok",
  },
  {
    id: 6,
    studentId: "6101010006",
    name: "Chaiwat Phongchai",
    email: "chaiwat.phongchai@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0812345683",
    grade: 5,
    class: "5/2",
    address: "67 Ramkhamhaeng Road, Bangkapi, Bangkok",
  },
  {
    id: 7,
    studentId: "6101010007",
    name: "Rachata Inthachai",
    email: "rachata.inthachai@gmail.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0812345684",
    grade: 5,
    class: "5/3",
    address: "88 Ratchadaphisek Road, Huay Kwang, Bangkok",
  },
  {
    id: 8,
    studentId: "6101010008",
    name: "Kanya Yodsuk",
    email: "kanya.yodsuk@gmail.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0812345685",
    grade: 5,
    class: "5/3",
    address: "55 Vibhavadi Road, Chatuchak, Bangkok",
  },
  {
    id: 9,
    studentId: "6101010009",
    name: "Prakob Wongchai",
    email: "prakob.wongchai@gmail.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0812345686",
    grade: 5,
    class: "5/3",
    address: "20 Sukhumvit Road, Wattana, Bangkok",
  },
  {
    id: 10,
    studentId: "6101010010",
    name: "Natnicha Chanthara",
    email: "natnicha.chanthara@gmail.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0812345687",
    grade: 5,
    class: "5/4",
    address: "91 Asoke Road, Wattana, Bangkok",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "Somchai Boonchai",
    students: ["Arthit Boonchai"],
    email: "somchai.boonchai@gmail.com",
    phone: "0812345678",
    address: "45 Soi Sukhumvit 22, Klongtoey, Bangkok",
  },
  {
    id: 2,
    name: "Niwat Suphan",
    students: ["Nicha Suphan"],
    email: "Niwat.suphan@gmail.com",
    phone: "0812345679",
    address: "32 Ladprao Road, Chatuchak, Bangkok",
  },
  {
    id: 3,
    name: "Somwan Yimprasert",
    students: ["Somchai Yimprasert"],
    email: "somwan.yimprasert@gmail.com",
    phone: "0812345680",
    address: "78 Charoenkrung Road, Bangrak, Bangkok",
  },
  {
    id: 4,
    name: "Armata Thongchai",
    students: ["Anong Thongchai", "Sarinya Thongchai"],
    email: "armata.thongchai@gmail.com",
    phone: "0812345681",
    address: "15 Silom Road, Bangrak, Bangkok",
  },
  {
    id: 5,
    name: "Pranom Kaewmanee",
    students: ["Sarinya Kaewmanee"],
    email: "pranom.kaewmanee@gmail.com",
    phone: "0812345682",
    address: "29 Phaholyothin Road, Chatuchak, Bangkok",
  },
  {
    id: 6,
    name: "Chaiwin Phongchai",
    students: ["Chaiwat Phongchai"],
    email: "Chaiwin.phongchai@gmail.com",
    phone: "0812345683",
    address: "67 Ramkhamhaeng Road, Bangkapi, Bangkok",
  },
  {
    id: 7,
    name: "Rachanee Inthachai",
    students: ["Rachata Inthachai", "Kanya Inthachai"],
    email: "rachanee.inthachai@gmail.com",
    phone: "0812345684",
    address: "88 Ratchadaphisek Road, Huay Kwang, Bangkok",
  },
  {
    id: 8,
    name: "Ophelia Yodsuk",
    students: ["Kanya Yodsuk"],
    email: "ophelia.yodsuk@gmail.com",
    phone: "0812345685",
    address: "55 Vibhavadi Road, Chatuchak, Bangkok",
  },
  {
    id: 9,
    name: "Prakob Wongchai",
    students: ["Prakob Wongchai", "Natnicha Wongchai"],
    email: "prakob.wongchai@gmail.com",
    phone: "0812345686",
    address: "20 Sukhumvit Road, Wattana, Bangkok",
  },
  {
    id: 10,
    name: "Natkanich Chanthara",
    students: ["Natnicha Chanthara"],
    email: "natkanich.chanthara@gmail.com",
    phone: "0812345687",
    address: "91 Asoke Road, Wattana, Bangkok",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Somchai Prasert", "Supaporn Meesuk"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Kritsada Wongchai", "Wiroj Phanit"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Sureeporn Chaiyawan", "Nongnuch Saowaluk"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Sureeporn Chaiyawan"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Anucha Srisuk", "Pichai Samut"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Kanchana Phongphrai"],
  },
  {
    id: 7,
    name: "Geometry",
    teachers: ["Somchai Prasert", "Supaporn Meesuk"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Somsak Yodchai"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Somsak Yodchai"],
  },
  {
    id: 10,
    name: "Literature",
    teachers: ["Wiroj Phanit"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "M1/1",
    capacity: 20,
    grade: 1,
    supervisor: "Somchai Prasert",
  },
  {
    id: 2,
    name: "M2/2",
    capacity: 22,
    grade: 2,
    supervisor: "Somchai Prasert",
  },
  {
    id: 3,
    name: "M3/3",
    capacity: 20,
    grade: 3,
    supervisor: "Somchai Prasert",
  },
  {
    id: 4,
    name: "M4/2",
    capacity: 18,
    grade: 4,
    supervisor: "Sureeporn Chaiyawan",
  },
  {
    id: 5,
    name: "M5/1",
    capacity: 16,
    grade: 5,
    supervisor: "Sureeporn Chaiyawan",
  },
  {
    id: 6,
    name: "M5/1",
    capacity: 20,
    grade: 5,
    supervisor: "Anucha Srisuk",
  },
  {
    id: 7,
    name: "M6/1",
    capacity: 18,
    grade: 7,
    supervisor: "Kritsada Wongchai",
  },
  {
    id: 8,
    name: "M6/2",
    capacity: 22,
    grade: 6,
    supervisor: "Nongnuch Saowaluk",
  },
  {
    id: 9,
    name: "M6/3",
    capacity: 18,
    grade: 6,
    supervisor: "Wiroj Phanit",
  },
  {
    id: 10,
    name: "M6/4",
    capacity: 20,
    grade: 6,
    supervisor: "Pichai Samut",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Peter Parker",
    student: "Peter Parker",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Peter Parker",
    student: "Peter Parker",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Peter Parker",
    student: "Peter Parker",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Peter Parker",
    student: "Peter Parker",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Peter Parker",
    student: "Peter Parker",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Peter Parker",
    student: "Peter Parker",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Peter Parker",
    student: "Peter Parker",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Peter Parker",
    student: "Peter Parker",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Peter Parker",
    student: "Peter Parker",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Peter Parker",
    student: "Peter Parker",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];

export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 10, 18, 8, 0),
    end: new Date(2024, 10, 18, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 10, 18, 9, 0),
    end: new Date(2024, 10, 18, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 10, 18, 10, 0),
    end: new Date(2024, 10, 18, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 10, 18, 11, 0),
    end: new Date(2024, 10, 18, 11, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 10, 18, 13, 0),
    end: new Date(2024, 10, 18, 13, 45),
  },
  {
    title: "Music",
    allDay: false,
    start: new Date(2024, 10, 19, 8, 0),
    end: new Date(2024, 10, 19, 8, 45),
  },
  {
    title: "Geometry",
    allDay: false,
    start: new Date(2024, 10, 19, 9, 0),
    end: new Date(2024, 10, 19, 9, 45),
  },
  {
    title: "Literature",
    allDay: false,
    start: new Date(2024, 10, 19, 10, 0),
    end: new Date(2024, 10, 19, 10, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 10, 19, 11, 0),
    end: new Date(2024, 10, 19, 11, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 10, 20, 8, 0),
    end: new Date(2024, 10, 20, 8, 45),
  },
  {
    title: "Spanish",
    allDay: false,
    start: new Date(2024, 10, 20, 9, 0),
    end: new Date(2024, 10, 20, 9, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 10, 20, 11, 0),
    end: new Date(2024, 10, 20, 11, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 10, 20, 14, 0),
    end: new Date(2024, 10, 20, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 10, 21, 8, 0),
    end: new Date(2024, 10, 21, 8, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 10, 21, 9, 0),
    end: new Date(2024, 10, 21, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 10, 21, 10, 0),
    end: new Date(2024, 10, 21, 10, 45),
  },
  {
    title: "Literature",
    allDay: false,
    start: new Date(2024, 10, 22, 8, 0),
    end: new Date(2024, 10, 22, 8, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 10, 22, 9, 0),
    end: new Date(2024, 10, 22, 9, 45),
  },
];
